site_name: Ringed Seal Detector
repo_url: https://github.com/karlzam/ringed-seal-detector/tree/main
github_repo: https://github.com/karlzam/ringed-seal-detector/tree/main
theme:
  name: readthedocs
  logo: logo-seal.png
plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - sane_lists
nav:
  - "index.md"
  - "About.md"
  - "SetUp.md"
  - "Usage.md"
  - "Credits.md"